---
- name: Setup VM
  hosts: all
  tasks:
    - block:
        - name: Add key to keyring file
          become: true
          ansible.builtin.apt_key:
            url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
            keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
        - name: Add gpg key
          shell: echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
        - name: install needed package
          become: true
          apt:
            update_cache: true
            name:
              - kubelet
              - kubeadm
              - kubectl
              - containerd
              - haproxy
              - keepalived
        - name: turn on engine module
          become: true
          shell: |
            modprobe br_netfilter
            echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
            echo "net.bridge.bridge-nf-call-iptables=1" >> /etc/sysctl.conf
            echo "net.bridge.bridge-nf-call-arptables=1" >> /etc/sysctl.conf
            echo "net.bridge.bridge-nf-call-ip6tables=1" >> /etc/sysctl.conf
            sysctl -p /etc/sysctl.conf
