---
- name: Install Clickhouse
  hosts: all
  vars_files: /home/vagrant/ansible/mnt-homeworks/08-ansible-02-playbook/playbook/group_vars/clickhouse/vars.yml
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_version }}_all.deb"
            dest: "./{{ item }}_{{ clickhouse_version }}.deb"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse-common-static distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/clickhouse-common-static/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
            dest: "./clickhouse-common-static_{{ clickhouse_version }}.deb"

    - name: Install package
      ansible.builtin.apt:
        force_apt_get: true
        deb: "{{ item }}"
      with_items:
        - /home/vagrant/ansible/mnt-homeworks/08-ansible-02-playbook/playbook/clickhouse-common-static_{{ clickhouse_version }}.deb
        - /home/vagrant/ansible/mnt-homeworks/08-ansible-02-playbook/playbook/clickhouse-server_{{ clickhouse_version }}.deb
        - /home/vagrant/ansible/mnt-homeworks/08-ansible-02-playbook/playbook/clickhouse-client_{{ clickhouse_version }}.deb

    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

- name: Install vector
  hosts: all
  vars_files: /home/vagrant/ansible/mnt-homeworks/08-ansible-02-playbook/playbook/group_vars/vector/vars.yml
  tasks:
    - block:
        - name: Get vector distrib
          ansible.builtin.get_url:
            url: "https://packages.timber.io/vector/{{ version }}/vector_{{ version }}-1_amd64.deb"
            dest: "./vector_{{ version }}-1.deb"

    - name: Install vector
      ansible.builtin.apt:
        deb: /home/vagrant/ansible/mnt-homeworks/08-ansible-02-playbook/playbook/vector_{{ version }}-1.deb
